version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ../..
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      DB_HOST: postgres
      SPRING_PROFILES_ACTIVE: prod